### ISSUE TITLE
Possible exclusion of Linux in list of platforms supported.

### ISSUE THREAD

**Issue by kotp** [exercism/xcpp#109]
> After reading an article, I visited your website for the first time. The first page that I clicked on said:
>
> "C++ runs on a variety of platforms, such as Windows, Mac OS, and the various versions of UNIX."
>
> http://exercism.io/languages/cpp/about

The part that seemed to be concerning to the reporter is the lack of a more direct reference to Linux.

**Comment by NobbZ** [comment]
Wikipedia (emphasis mine):

> Linux [...] is a **Unix-like`** computer operating system assembled under the model of free and open-source software development and distribution.

So linux is covered. 

But I have to admit "runs" feels wrong. C++ as a language does not "run" anywhere, I'd prefer to say "Compilers for C++ are available for a variety ..."

**Comment by kotp** [comment]
I thought it was covered solely with the phrase "such as" myself.  But... low hanging fruit for clarity.
