### ISSUE TITLE
Override probot/stale defaults, if necessary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcpp#117]
Per the discussion in https://github.com/exercism/discussions/issues/128 we
will be installing the probot/stale integration on the Exercism organization on
April 10th, 2017.

By default, probot will comment on issues that are older than 60 days, warning
that they are stale. If there is no movement in 7 days, the bot will close the issue.
By default, anything with the labels `security` or `pinned` will not be closed by
probot.

If you wish to override these settings, create a .github/stale.yml file as described
in https://github.com/probot/stale#usage, and make sure that it is merged
before April 10th.

If the defaults are fine for this repository, then there is nothing further to do.
You may close this issue.

**Comment by kytrinyx** [comment]
I made a mistake.

This was not explicitly documented in the README, but probot/stale **requires the presence of a .github/stale.yml** file.

If you want the default behavior, you need to add an empty .github/stale.yml file to this repo, otherwise the bot will not be active.

**Comment by morrme** [comment]
i dont see this file as having been created. is it only viewable to admins @kytrinyx ?

**Comment by NobbZ** [comment]
No. If it were there, everyone could see it. It simply hasn't been added.

**Comment by patricksjackson** [comment]
Yea, I haven't added it yet.

Mostly that is because I've been _slowly_ working on cleaning up some of the very old (but still relevant) issues around here, and because I'm the only one maintaining the track. Since I don't have the time every week to come in and contribute, it would just end up reminding me how little free time I actually have.

With 1 or 2 other people actively reviewing PR's or clearing up issues, that wouldn't be a problem.

I do think this is a great idea, by the way. This track just isn't in a state where it makes sense to enable it yet.

**Comment by kytrinyx** [comment]
I think on many of the language tracks it doesn't make sense to add it. Our worst problem was the main exercism/exercism.io repo. I think it would be fine to close this issue and then reconsider adding probot/stale in 6 or so months... if we think of it. Or just wait until we start seeing a bunch of stale issues that we wish a bot would take care of for us.

**Comment by morrme** [comment]
@kytrinyx I haven't participated in the ongoing "un/undermaintained tracks" discussion because I am not a maintainer but this is a great sort of task for a ...well I don't know of a good word but a "sub" maintainer? Anyway....like auditing issues on a regular basis , seeing how many have been resolved but not closed , or seeing if some even still apply. I've pinged you on some lately just as someone who wants to continue contributing but I see it as a cool "role" that someone could do to support an undermaintained track.

**Comment by kytrinyx** [comment]
It's such a huge help, @morrme. I wonder if we could create a "curator" team (or some other name) for this type of work. It's so essential, and it should be recognized properly!

**Comment by kytrinyx** [comment]
I did like the suggestion of having "Unmaintainers" :-) It's a bit tongue in cheek, but kind of works.

**Comment by morrme** [comment]
It is great for people who may not think they're advanced enough in the language itself, but want to support. Alternatively, everyone could be considered a "maintainer" but then given a role like this within the team as their primary focus. That would eliminate any "greater than"/"less than" feelings, if they arose. 

It can also be good for some of the track maintainers who would agree to support an additional track...like they can be their own track's primary maintainer, but do "unmaintainer" things for another track, by title or by role.

**Comment by kytrinyx** [comment]
Yeah. I don't want greater than / less than feelings. Keeping this machine running takes all of us, and this sort of mark-and-sweep behavior is critical to making it easy for people to see what work can be tackled, or where things are missing.

**Comment by morrme** [comment]
Definitely. As someone who is not an expert in every language, I've found tasks that I could help with, in addition to unofficially "botting" some of the older issues. I have learned a lot just from being able to do that. I think more people would have the confidence to be a maintainer if they knew there were tasks they could be responsible for regularly that were within their "reach".  The best part is, in the spirit of this org, they can grow into more responsibilities as confidence/skill increases, which helps keep these tracks alive !

**Comment by morrme** [comment]
@kytrinyx and if you ever need any volunteers once everyone else is reshuffled, I'm happy to support.

**Comment by kytrinyx** [comment]
@morrme 💛 💙 💚 ❤️ 💜 You're on!

**Comment by patricksjackson** [comment]
A _lot_ of the work that goes into maintaining a track requires just a basic knowledge of the language and an understanding of how the Exercism tracks are setup and integrate together.

In truth, I think some of the tracks could benefit enormously from someone who is actively learning the language and willing to contribute, either as a maintainer or not. Figuring out exercise difficulty (see #124), ease of setup (see the many _many_ threads about that here), and improving the documentation are probably easier for a language learner than for someone already familiar with the language. Also, going through the process to get a new exercise added to a track can be a great learning experience.

I'm going to close this issue as @kytrinyx suggested. If there are ever more people actively contributing for this track maybe we will add it in the future.

Thanks

**Comment by kytrinyx** [comment]
> In truth, I think some of the tracks could benefit enormously from someone who is actively learning the language and willing to contribute, either as a maintainer or not.

💯 times this!
