### ISSUE TITLE
Critera for test pass on cpp and python differ for word-count

### ISSUE THREAD

**Issue by joseph-fourier** [exercism/xcpp#24]
Another one I spotted. :)

The cpp tests require you to ignore punctuation and case:

``` cpp
BOOST_AUTO_TEST_CASE(normalizes_case)
{
    const map<string, int> expected{{"go", 3}};

    const auto actual = word_count::words("go Go GO");

    REQUIRE_EQUAL_CONTAINERS(expected, actual);
}
BOOST_AUTO_TEST_CASE(ignores_punctuation)
{
    const map<string, int> expected{{"car", 1}, {"carpet", 1}, 
        {"as", 1}, {"java", 1}, {"javascript", 1}};

    const auto actual = word_count::words("car : carpet as java : javascript!!&@$%^&");

    REQUIRE_EQUAL_CONTAINERS(expected, actual);
}

```

The python tests require you to preserve both of these:

``` python
def test_preserves_punctuation(self):
    self.assertEqual(
        {'car': 1, 'carpet': 1, 'as': 1, 'java': 1, ':': 2, 'javascript!!&@$%^&': 1},
        word_count('car : carpet as java : javascript!!&@$%^&')
    )

def test_mixed_case(self):
    self.assertEqual(
        {'go': 1, 'Go': 1, 'GO': 1},
        word_count('go Go GO')
    )
```

It would be good to have consistency.

Links:
https://github.com/exercism/xcpp/blob/master/word-count/word_count_test.cpp
https://github.com/exercism/xpython/blob/master/word-count/word_count_test.py

**Comment by patricksjackson** [comment]
I don't think this needs to be handled. X-common settled on normalization [with this commit](https://github.com/exercism/x-common/commit/2a88ba1bacfc147af5f0dd78fca23c305d1ab218).

In addition, normalizing in Cpp is actually a good thing to know how to do. There isn't a stdlib function to force a whole string to lowercase.

**Comment by kytrinyx** [comment]
@patricksjackson Good point. We've been back and forth on this a lot in the past couple of years.
