### ISSUE TITLE
Problem testing word-count on C++

### ISSUE THREAD

**Issue by camponez** [exercism/xcpp#37]
I started with "Word_count".

Everything setup ok and I run make to get an expected error:

==============

$ make
Scanning dependencies of target word-count
[ 50%] Building CXX object CMakeFiles/word-count.dir/word_count_test.cpp.o
/home/camponez/exercism/cpp/word-count/word_count_test.cpp: In member function ‘void counts_one_word::test_method()’:
/home/camponez/exercism/cpp/word-count/word_count_test.cpp:28:25: error: ‘word_count’ has not been declared
     const auto actual = word_count::words("word");
                         ^
CMakeFiles/word-count.dir/build.make:54: recipe for target 'CMakeFiles/word-count.dir/word_count_test.cpp.o' failed
make[2]: *** [CMakeFiles/word-count.dir/word_count_test.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/word-count.dir/all' failed
make[1]: *** [CMakeFiles/word-count.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

==================

After I implement an empty class just to get to the first fail test, I got an *unexpected* error:

==================
$ make
Scanning dependencies of target word-count
[ 50%] Building CXX object CMakeFiles/word-count.dir/word_count_test.cpp.o
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from /home/camponez/exercism/cpp/word-count/word_count_test.cpp:3:
/usr/include/boost/test/test_tools.hpp: In instantiation of ‘boost::test_tools::predicate_result boost::test_tools::tt_detail::equal_coll_impl(Left, Left, Right, Right) [with Left = std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char>, int> >; Right = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >]’:
/home/camponez/exercism/cpp/word-count/word_count_test.cpp:30:5:   required from here
/usr/include/boost/test/test_tools.hpp:639:25: error: no match for ‘operator!=’ (operand types are ‘const std::pair<const std::basic_string<char>, int>’ and ‘const char’)
         if( *left_begin != *right_begin ) {
                         ^
/usr/include/boost/test/test_tools.hpp:639:25: note: candidates are:
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/test/predicate_result.hpp:24,
                 from /usr/include/boost/test/test_tools.hpp:19,
                 from /usr/include/boost/test/unit_test.hpp:19,
                 from /home/camponez/exercism/cpp/word-count/word_count_test.cpp:3:
/usr/include/boost/smart_ptr/shared_ptr.hpp:738:40: note: template<class T, class U> bool boost::operator!=(const boost::shared_ptr<X>&, const boost::shared_ptr<U>&)
 template<class T, class U> inline bool operator!=(shared_ptr<T> const & a, shared_ptr<U> const & b) BOOST_NOEXCEPT
                                        ^

<MANY LINES OF ERROR HERE>

/usr/include/c++/4.9/bits/stl_iterator.h:822:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from /home/camponez/exercism/cpp/word-count/word_count_test.cpp:3:
/usr/include/boost/test/test_tools.hpp:639:25: note:   ‘const std::pair<const std::basic_string<char>, int>’ is not derived from ‘const __gnu_cxx::__normal_iterator<_IteratorL, _Container>’
         if( *left_begin != *right_begin ) {
                         ^
CMakeFiles/word-count.dir/build.make:54: recipe for target 'CMakeFiles/word-count.dir/word_count_test.cpp.o' failed
make[2]: *** [CMakeFiles/word-count.dir/word_count_test.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/word-count.dir/all' failed
make[1]: *** [CMakeFiles/word-count.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

========================

What am I doing wrong?

**Comment by LegalizeAdulthood** [comment]
Hi, sorry for the delay in responding to this, I only just noticed it now.

Best practices in C++ are to put all of your own stuff inside a namespace with the exception of `main` which must be in the global scope.  The exercises are all coded with this in mind, so the tests invoke the function `words` inside the namespace `word_count`.  I tried to include the necessary stuff in the test file so that `std::map` would print OK with Boost.Test.  They have had a couple releases since then, so perhaps my magic sauce is no longer working and that is why you are getting this compile error.  I will take some time to investigate this with the latest release of Boost.  Without seeing your code, I can't see if there is an unexpected interaction between your code and the test that is causing this.

You can take a look at [my solution](http://exercism.io/submissions/f158be5966a57a8b7496d5df) if it helps.

**Comment by camponez** [comment]
Thanks for your reply! I didn't no about this best namespace practices! I'll try again using namespace.

**Comment by LegalizeAdulthood** [comment]
You're welcome!  You're not the first person to see `foo::bar` in the test code and automatically think this meant a static function `bar` on a class `foo`.  I will probably add something to the documentation to explain best practices here.

**Comment by camponez** [comment]
I was trying to figure out what types to return. I was using list<string> at first and that is why I got this error!

I was expecting a better error from the compiler though. :)

**Comment by LegalizeAdulthood** [comment]
Was it the use of `auto` that threw you off?  I tried to make it clear that the function should return a map of strings to integers by declaring `expected` as `std::map<std::string, int>`

**Comment by camponez** [comment]
Not really. I was trying to figure it out without looking at the test's source code, just guessing by the error, and it does not show map. 

After I look at the test source it became clear.

The whole problem start because these *huge* error didn't seem be, at all, because of the return type. I just thought I had miss some package or something else.

**Comment by camponez** [comment]
By the way, 

> You can take a look at my solution if it helps.

I like your solution, very neat. However it does not pass on "with_apostrophes" and "with_apostrophes_as_quotes" tests.

**Comment by LegalizeAdulthood** [comment]
Oh, I remember now.  Someone else added test cases for this and my reference solution in the repo was updated but I hadn't updated my submission on exercism.

**Comment by LegalizeAdulthood** [comment]
I think this is related to https://github.com/exercism/xcpp/issues/44 where we could improve the documentation on dealing with chatty compilers.  @camponez I'm going to close this issue as I think the documentation improvement is the right way to go on this.  Please re-open the issue if there is anything else you need.
