### ISSUE TITLE
update docs -- multiple files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcpp#40]
Someone mentioned that the C++ track says that you can't submit multiple files.

For the longest time this was true, but we recently managed to finish adding support for this.

```
exercism submit file1 file2 file3
```

When someone has a moment, it would be nice to verify that this actually works and does what you would expect, and then update the docs.

**Comment by LegalizeAdulthood** [comment]
I'll see if I can get some time this weekend to try this out.  If it works OK, I'll update the docs and my posted solutions.

**Comment by kytrinyx** [comment]
sweet, thanks!

**Comment by patricksjackson** [comment]
This was already taken out with [this commit](https://github.com/exercism/xcpp/commit/ee23d68f24ad74f928f590f26655467c8c5c96a6)

**Comment by kytrinyx** [comment]
Nice! Closing.
