### ISSUE TITLE
Accommodate both Xcode and homebrew gcc on C++

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/xcpp#45]
Mac users have a choice of using Xcode, or gcc via homebrew as their compiler.

The build script should be updated to accommodate both use cases.

**Comment by masters3d** [comment]
How can I help with this? I don't know much about *building* but I'd like to use LLVM instead of GCC in xcode.

**Comment by masters3d** [comment]
Forgive my noobness on this, but is there another unit test framework that does not require a make script for building?
https://github.com/philsquared/Catch/blob/master/docs/why-catch.md

**Comment by LegalizeAdulthood** [comment]
Have you tried it with Xcode?  I don't know what happens in that situation because I don't have a Mac for testing.

Regarding Catch, we need boost for some other facilities anyway (calendars and filling in regex gaps), so using that for the unit tests is "free".  Also, requiring boost gives you access to many things like string algorithms that make the solutions cleaner and more idiomatic.

**Comment by masters3d** [comment]
Do you think this is related ? I am working on the first problem using xcode and clang

```
/usr/local/include/boost/test/tools/detail/print_helper.hpp:50:14: 
Invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const std::__1::pair<const std::__1::basic_string<char>, int>')
```

![image](https://cloud.githubusercontent.com/assets/6539412/15803399/6a1339f6-2a90-11e6-9c17-0b3ed73b0762.png)

**Comment by masters3d** [comment]
I applied the xcode fix it which just added a & to t. I am using boost 1.60.0_1 from homebrew on the mac. 

I successfully used clang on my mac using cmake 3.5 except for the little fix to boost above. 

**I don't think the GCC option should be supported on the build script.**

if people want to use GCC and they have it installed they can just choose it under the xcode project. 

![image](https://cloud.githubusercontent.com/assets/6539412/15834534/ca9e05c0-2be0-11e6-814f-eb0b7c4dbf67.png)



```
$ cmake -G Xcode
-- The CXX compiler identification is AppleClang 7.3.0.7030029
-- Check for working CXX compiler using: Xcode
-- Check for working CXX compiler using: Xcode -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   unit_test_framework
--   date_time
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /exercismProblems/cpp/bob
```

**Comment by masters3d** [comment]
Something weird with going on: I need to add the below to the bob exercise to make it compile. Do you know why? 

``#define BOOST_REQUIRE_EQUAL( L, R )\
    BOOST_REQUIRE_EQUAL( L, R )
``

**Comment by masters3d** [comment]
this is the error that gets fixed once I apply #define BOOST_REQUIRE_EQUAL( L, R )\ BOOST_REQUIRE_EQUAL( L, R ) 
![image](https://cloud.githubusercontent.com/assets/6539412/15838469/050df92e-2bf3-11e6-9690-ad03908f4a25.png)

**Comment by masters3d** [comment]
Sorry about all the noise. I fixed this error. It was just a namespace issue!

**Comment by LegalizeAdulthood** [comment]
Thanks
