### ISSUE TITLE
nucleotide-count, invalid input

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcpp#50]
The tests do expect that I throw an exception, when I ask for the count of `X`, but calling the constructor with invalid DNA seems to be ok, there are no tests for `const dna::counter dna { "X" }`.

Is there any special reason why this one was left out?

In the other tracks I have solved this, similar cases were expected to raise/throw/error out.

**Comment by LegalizeAdulthood** [comment]
It would be a good addition to add a test for this.  Pull requests are always welcome :smile_cat:

**Comment by NobbZ** [comment]
I'll sit down later this day and take look what redressed would make sense or are else missing.

**Comment by LegalizeAdulthood** [comment]
Throwing [`invalid_argument`](http://en.cppreference.com/w/cpp/error/invalid_argument) seems to be the right thing.

**Comment by LegalizeAdulthood** [comment]
[This test case](https://github.com/exercism/xcpp/blob/9b5d173ed0b0317bcf154e516fbd534c2cb8b217/nth-prime/nth_prime_test.cpp) gives an example of how to write a test that verifies an exception of a specific type was thrown under a certain circumstance.
