### ISSUE TITLE
Inconsistency in `triangle`s test

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcpp#59]
There is some inconsistency in the tests for `triangle` exercise.

The tests do expect to throw an `DomainError` when all sides of the triangle are `0`, but to return `triangle::illegal` when we have negative length sides or don't fullfil the triangle inequality.

To make this consistent, we should either throw something in all three cases or return `triangle::illegal` in all cases.

To line up with other tracks that support some kind of throwing, I think we should throw in every case and get rid of `triangle::illegal`.

**Comment by LegalizeAdulthood** [comment]
This seems like a good idea to me.  Pull requests are welcome :smile_cat:

**Comment by NobbZ** [comment]
Pull requests in favor of keeping or dropping illegal in the enum?

**Comment by LegalizeAdulthood** [comment]
Throwing `domain_error` seems more appropriate.

**Comment by NobbZ** [comment]
I'll try to get the PR ready during the rest of my year, I've still a
little bit more than 3 hours left.

Richard Thomson <notifications@github.com> schrieb am Do., 31. Dez. 2015
20:42:

**Comment by NobbZ** [comment]
I'll not be able to do it before years end... Some kids from the
neighborhood scared my 4 year old son by throwing some huge firecrackers
early...

Norbert Melzer <timmelzer@gmail.com> schrieb am Do., 31. Dez. 2015 20:49:
