### ISSUE TITLE
Compilation error for word-count problem

### ISSUE THREAD

**Issue by Stvad** [exercism/xcpp#61]
I've started on cpp track recently and I have problems compiling the second task (word-count problem). http://pastebin.com/RyHTtAje - this is compile output I'm getting. As I understand - although there is code in a test suit to teach boost to print std::pair's :
```
namespace boost
{
// teach Boost.Test how to print std::pair
template <typename K, typename V>
inline wrap_stringstream&
operator<<(wrap_stringstream& wrapped, std::pair<const K, V> const& item)
{
    return wrapped << '<' << item.first << ',' << item.second << '>';
}
}
```
boost is not really in the mood to learn..

**Comment by LegalizeAdulthood** [comment]
Thanks for your feedback.  I have a fix for this in progress and I am waiting on some testing to confirm that it addresses the issue.  We should have an update for this in a day or two.

**Comment by LegalizeAdulthood** [comment]
As a workaround you can use a Boost distribution >= 1.55 and < 1.59.  In 1.59 they made big changes and this broke my helper functions that assist in printing out vectors and maps.

**Comment by oalbe** [comment]
@LegalizeAdulthood Pardon the question: is there any plan to upgrade to the last version of Boost? It's been quite a while since 1.55, and it does not work on a lot of recent platforms (e.g. VS2015).

**Comment by LegalizeAdulthood** [comment]
Have you tried 1.58?  That should work fine.

The current unit tests have a problem with 1.59 and 1.60.  I have a fix for that, but I'm trying to [work out an issue on Mac](https://github.com/exercism/xcpp/pull/58) before deploying that update.

**Comment by oalbe** [comment]
No I haven't tried 1.58 (though I have tried both 1.55 and 1.59. Both had problems of different nature), but if you say that you're going to update to 1.60 in the near future I'll wait :)

**Comment by LegalizeAdulthood** [comment]
What I'm going to deploy is code for the test suites that works with any Boost version from 1.55 onwards.  The existing CMake recipe requires a Boost of at least 1.55, but in Boost 1.59 and later the mechanisms for print the contents of `std::vector` and `std::map` in diagnostic messages changed.  In 1.59 they made significant changes to Boost.Test which is when the problem first came up.  So you can use 1.58 as a stopgap; I hope to have the 1.59+ changes deployed soon, I just need help testing on MacOS.

**Comment by LegalizeAdulthood** [comment]
In case you're curious, you can look at the [boost branch](https://github.com/exercism/xcpp/tree/boost) on github for what I'm currently testing.

**Comment by oalbe** [comment]
@LegalizeAdulthood I didn't think it was possible to write code compliant to both 1.55 and 1.59+ since, asking in the #boost channel on freenode they told me that the chances to the 1.59 were pretty big (as you pointed out). But if it's possible, well, win-win. I'm on Windows (8.1 for what matters) otherwise I would gladly help you test for OSX.

I'll definitely give a look at the branch, though I have literally zero knowledge of Boost, so I don't think I will be able to help at all, unfortunately.

**Comment by LegalizeAdulthood** [comment]
I had to dip into the implementation details a little bit in order to make the pretty-printer understand `vector` and `map`.  It is not unexpected that this part of the code would be fragile to big changes in Boost.Test, but a similar approach works in 1.59 and 1.60.

**Comment by MarkGartland** [comment]
I tried building word-count commit 4002564 on OS X 10.10.5, using Boost 1.60.  Xcode (v7.2) failed with this error: "/usr/local/boost_1_60_0/boost/test/tools/detail/print_helper.hpp:50:14: Call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup". Boost, Cmake, and Xcode are all new to me, so the error could certainly be my fault. Nevertheless, I'd like to help. What can I do for you?

**Comment by LegalizeAdulthood** [comment]
@MarkGartland Thanks for the offer!  I don't think there's much that you can do for me.  I simply need to get ahold of a Mac myself and figure out the right solution.

**Comment by masters3d** [comment]
I was able to build using boost 1.6 and xcode 7.3 with Clang. There was a small change that Xcode wanted me to do to boost print help function. see. https://github.com/exercism/xcpp/issues/45

**Comment by masters3d** [comment]
I stated on bob and I was getting some weird link errors that get fixed if I overload the boost preprocessor. 
In bob this fixes it. 

``#define BOOST_REQUIRE_EQUAL( L, R )\
    BOOST_REQUIRE_EQUAL( L, R )
``

**Comment by LegalizeAdulthood** [comment]
I believe this issue is now resolved on all platforms; please re-open it if you still encounter the problem.
