### ISSUE TITLE
Move exercises to subdirectory

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcpp#63]
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

Ref: https://github.com/exercism/exercism.io/issues/3336

**Comment by LegalizeAdulthood** [comment]
Does this only affect the xcpp repo or does it also affect what the user sees when they fetch exercises for a language track?

**Comment by kytrinyx** [comment]
It only affects the xcpp repo -- everything else is unchanged.

**Comment by masters3d** [comment]
@LegalizeAdulthood  Could I submit a PR for this with out breaking the build scripts?

**Comment by LegalizeAdulthood** [comment]
You can always submit a pull request.  If it breaks the build scripts, I believe travis will show that when it runs an integration build on the branch.  We can look at the build log and see what (if anything) needs to be fixed.

**Comment by petertseng** [comment]
Hello, since #108 is merged, let's close this!

**Comment by kytrinyx** [comment]
Good call. Thanks!
