### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcpp#65]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by kytrinyx** [comment]
There was a bit of confusion with this issue. I've summarized my current understanding here: https://github.com/exercism/x-common/issues/202

I am closing this issue. If necessary I will open a new issue once we have come to an agreement about how to resolve the inconsistencies and what exact steps to take.

**Comment by LegalizeAdulthood** [comment]
For C++ we can address this by changing this test case to avoid the strict equality:

```
BOOST_AUTO_TEST_CASE(medium_triangles_violating_triangle_inequality_are_illegal)
{
    BOOST_REQUIRE_THROW(triangle::kind(2, 4, 2), std::domain_error);
}
```

**Comment by kytrinyx** [comment]
The problem here is the subtle difference between violating the triangle inequality, and not violating it but being degenerate. 2, 4, 2 doesn't violate the basic triangle inequality.

**Comment by LegalizeAdulthood** [comment]
The test is reporting it as a violation (throwing `std::domain_error` exception)

**Comment by kytrinyx** [comment]
Right, according to the triangle inequality, 2, 4, 2 is _not_ in violation (it just specifies a degenerate triangle).

I think that it would be easier to avoid the exact edge case and use 5, 5, 11 as the input, which clearly violates the inequality.
