### ISSUE TITLE
Test cases for etl use char. Readme says data type should be string.

### ISSUE THREAD

**Issue by lhbhl** [exercism/xcpp#68]
The README for etl exercise states:

"Note that both the old and the new system use strings to represent letters, even in languages that have a separate data type for characters."

Yet the supplied c++ test cases use char for letters. Is this intended?

**Comment by LegalizeAdulthood** [comment]
It appears to be an oversight.  I largely implemented the C++ track by imitating the JavaScript track and referencing the problem statements and I appear to have simply missed this 'note' at the bottom of the test file.

**Comment by kytrinyx** [comment]
Ah, we need to remove the datatype stuff from the README. This is wildly out of date.

**Comment by kytrinyx** [comment]
Fixed in the README, I'll deploy today.

**Comment by LegalizeAdulthood** [comment]
OK, great, nothing for me to do then, LOL.  :smile_cat:

It seems perfectly natural for this problem to use a data type for characters if you have it.

**Comment by kytrinyx** [comment]
Agreed. And runes in Go. I don't recall why that old bit of lore ended up in the README to be honest.
