### ISSUE TITLE
Ordering of exercises

### ISSUE THREAD

**Issue by k4rtik** [exercism/xcpp#79]
I notice that exercise leap is relatively later in the track, while being cognitively much simpler than exercises like word-count. It would be great to have the exercises ordered by increasing difficulty.

**Comment by k4rtik** [comment]
I might have wrong here to (over) generalize that exercises aren't ordered correctly in C++ track. This issue probably can just deal with order of leap.

**Comment by kytrinyx** [comment]
I noticed in the Go track that we kept adding exercises at approximately where we thought they belonged, and it caused a couple of simple exercises to get pushed later in the track without meaning to.

I do think Leap could go earlier in the track.

**Comment by LegalizeAdulthood** [comment]
I followed the JavaScript track ordering at the time I created the C++ track.  I agree with the sentiment that the exercises should get progressively harder, but one person's "easy" is another person's "hard", so the order will always be at odds with someone's idea of difficulty.

Patches welcome :)

**Comment by k4rtik** [comment]
[Working](https://docs.google.com/spreadsheets/d/1WAdTknhr2NsVsDRRFIfrZAC5m8kPNZb0sdod7qdaYzY/edit?usp=sharing) on it.
