### ISSUE TITLE
Create C++ gitter room

### ISSUE THREAD

**Issue by masters3d** [exercism/xcpp#83]
https://gitter.im/exercism/

**Comment by LegalizeAdulthood** [comment]
What is a gitter room and how do you create one?

**Comment by masters3d** [comment]
gitter is a support chat room for people with questions about the c++ problems, you can make one on the web link based on this repo like some other tracks already have done.

**Comment by LegalizeAdulthood** [comment]
And once we make it, how to people discover it?

**Comment by masters3d** [comment]
right now only on the “support chat”  http://exercism.io/help <http://exercism.io/help>

but soon on each track on the website hopefully

https://github.com/exercism/exercism.io/pull/2893#issuecomment-220523354 <https://github.com/exercism/exercism.io/pull/2893#issuecomment-220523354>

**Comment by LegalizeAdulthood** [comment]
I think I've seen a "gitter" button on some repo README.md's -- do you think that is useful?

**Comment by masters3d** [comment]
I think so so ver simple questions that are not "googleable"

**Comment by kytrinyx** [comment]
I've opened an issue here: https://github.com/exercism/discussions/issues/43

I suggest that we close this issue in favor of figuring out how we want to deal with this overall, and then we can write up a meaty issue to post to all the tracks at once.

**Comment by LegalizeAdulthood** [comment]
Closed until we figure out the best way to do this.
