### ISSUE TITLE
C++ naming conventions

### ISSUE THREAD

**Issue by masters3d** [exercism/xcpp#84]
Is there an specific naming convention to follow with this repo?

For example. 
``anagram::anagram``
Do we make all the Types upper case as in google style guide? etc

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

**Comment by LegalizeAdulthood** [comment]
This repo follows the naming convention of the standard library, so `names_are_like_this`.  Every organization seems to have it's own naming convention in C++, whereas Java and C# seem to have adopted the naming convention of their respective languages progenitors.  For whatever reason, in C++ this didn't happen.
